Weather/Weather.Web/Models/ErrorViewModel.cs
using System;

namespace Weather.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Weather/Weather.Web/Controllers/WeatherController.cs
using System;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Weather.Core;
using Weather.Web.Models;

namespace Weather.Web.Controllers
{
    public class WeatherController : Controller
    {
        private readonly IWeatherProvider _weatherProvider;
        private readonly ILogger<WeatherController> _logger;

        public WeatherController(IWeatherProvider weatherProvider, ILoggerFactory loggerFactory)
        {
            _weatherProvider = weatherProvider ?? throw new ArgumentNullException(nameof(weatherProvider));
            _logger = loggerFactory.CreateLogger<WeatherController>();
        }

        public async Task<IActionResult> ToDay()
        {
            try
            {
                var weatherInfo = await _weatherProvider.ToDay();

                return View(weatherInfo);
            }
            catch (Exception e)
            {
                _logger.Log(LogLevel.Error, e, "Cannot get weather from provider");

                return RedirectToAction("Error");
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

Weather/Weather.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WeatherInfo</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Weather" asp-action="ToDay">Today</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark"  href="#">Tomorrow</a>
                        </li> 
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - WeatherInfo.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Weather/Weather.Web/Views/Weather/ToDay.cshtml
@model Weather.Core.WeatherInfo

@{
    ViewBag.Title = "Today";
    Layout = "_Layout";
}

<h2>Weather @Model.City</h2>

<table class="table">
    <tbody>
    <tr>
        <td>@nameof(Model.Description)</td>
        <td>@Model.Description</td>
    </tr>
    <tr>
        <td>@nameof(Model.Visibility)</td>
        <td>@Model.Visibility</td>
    </tr>
    <tr>
        <td>@nameof(Model.Cloud)</td>
        <td>@Model.Cloud</td>
    </tr>
    <tr>
        <td>@nameof(Model.Sunrise)</td>
        <td>@Model.Sunrise</td>
    </tr>
    <tr>
        <td>@nameof(Model.Sunset)</td>
        <td>@Model.Sunset</td>
    </tr>
    <tr>
        <td>Wind.Speed</td>
        <td>@Model.Wind.Speed</td>
    </tr>
    <tr>
        <td>Wind.Deg</td>
        <td>@Model.Wind.Deg</td>
    </tr>
    <tr>
        <td>@nameof(Model.Main.Temperature)</td>
        <td>@Model.Main.Temperature</td>
    </tr>
    <tr>
        <td>@nameof(Model.Main.Humidity)</td>
        <td>@Model.Main.Humidity</td>
    </tr>
    <tr>
        <td>@nameof(Model.Main.MaxTemperature)</td>
        <td>@Model.Main.MaxTemperature</td>
    </tr>
    <tr>
        <td>@nameof(Model.Main.MinTemperature)</td>
        <td>@Model.Main.MinTemperature</td>
    </tr>
    <tr>
        <td>@nameof(Model.Main.Pressure)</td>
        <td>@Model.Main.Pressure</td>
    </tr>
    </tbody>
</table>